### ISSUE TITLE
ERROR: spawn npm ENOENT

### ISSUE THREAD

**Issue by npdevapp** [oracle/bots-node-sdk#3]
Hi,

While running the command, "bots-node-sdk init --run", I am continuously getting this error. Tried all options but to no avail.
**************************************************************************
D:\np\mywork\initiatives\chatbots\oda\scc_customcomp>bots-node-sdk init --run
---------------------------------------------------------------------
Will update contents in directory 'scc_customcomp'
Create component package in directory 'scc_customcomp'...
---------------------------------------------------------------------

Writing files...

WARN: D:\np\mywork\initiatives\chatbots\oda\scc_customcomp\main.js already exists
WARN: D:\np\mywork\initiatives\chatbots\oda\scc_customcomp\package.json already exists
WARN: D:\np\mywork\initiatives\chatbots\oda\scc_customcomp\README.md already exists
WARN: D:\np\mywork\initiatives\chatbots\oda\scc_customcomp\spec\test.req.json already exists
WARN: D:\np\mywork\initiatives\chatbots\oda\scc_customcomp\.gitignore already exists
WARN: D:\np\mywork\initiatives\chatbots\oda\scc_customcomp\.npmignore already exists

Installing dependencies...

ERROR: spawn npm ENOENT
**************************************************************************

**Comment by mvandervliet** [comment]
Resolved in [v2.1.3](https://github.com/oracle/bots-node-sdk/releases/tag/v2.1.3)
