### ISSUE TITLE
Basic Authentication / OAuth Support

### ISSUE THREAD

**Issue by riyadshauk** [oracle/bots-node-sdk#4]
**Use Case**: There may be a use case where a user wants to deploy their custom code on their own server (maybe to use other dependencies not supported on Oracle Mobile Hub); however, the server may not be authenticated.

**Problem**: It would be great to have support for Basic Authentication (or OAuth) when deploying a custom component that depends on this @oracle/bots-node-sdk package in their package.json.

**Solution**: Can the @oracle/bots-node-sdk support a config file in the user's custom component code which will easily/declaratively enable basic authentication support (ie, a JSON)?

**Problem Pt 2**: Can OAuth 2.0 be supported?
**Solution 2**: Can the Express object be exposed by the @oracle/bots-node-sdk to allow for custom decorations for using middlewares which would enable Basic Authentication or OAuth 2.0 or whatever next-gen authentication method might come next?

**Comment by mvandervliet** [comment]
Thanks @riyadshauk,

In general, this package is designed to supply the necessary middleware for integrating with with the ODA platform, which may be used _in conjunction with_ other services or middleware for any customization needs. Such services might include Logging, Auth, metrics, etc.. This is purely another middleware layer. 

As an example for the case of Basic Authentication support, one might implement a standalone service in a manner such as:

> `./server.js`

```javascript
const express = require('express');
const app = express();
const auth = require('basic-auth');
const OracleBot = require('@oracle/bots-node-sdk');

// add basic auth middleware
const { AUTH_USER = 'user', AUTH_PASS = 'pass' } = process.env;
app.use((req, res, next) => {
  const basic = auth(req);
  if (basic && basic.name === AUTH_USER && basic.pass === AUTH_PASS) {
    next();
  } else {
    res.status(401)
      .set('WWW-Authenticate', 'Basic realm="ODA Custom Component Service"')
      .end('Access denied');
  }
});

// add custom component middleware
OracleBot.Middleware.customComponent(app, {
  baseUrl: '/components',
  register: './components'
});

app.listen(process.env.PORT || 3000, () => {
  console.log('Listening with auth');
});
```
